const words = [
    "Aberration: A departure from what is normal, usual, or expected.",
    "Abscond: To leave hurriedly and secretly.",
    "Abstruse: Difficult to understand.",
    "Acrimony: Bitterness or ill feeling.",
    "Adulation: Excessive admiration or praise.",
    "Aesthetic: Concerned with beauty or the appreciation of beauty.",
    "Alacrity: Cheerful readiness or eagerness.",
    "Alleviate: To make less severe.",
    "Ambiguous: Open to more than one interpretation.",
    "Ambivalent: Having mixed feelings or contradictory ideas.",
    "Amicable: Having a spirit of friendliness.",
    "Analogous: Comparable in certain respects.",
    "Anecdote: A short, amusing story about a real incident.",
    "Anomaly: Something that deviates from the norm.",
    "Antithesis: A person or thing that is the direct opposite of someone or something else.",
    "Apathy: Lack of interest, enthusiasm, or concern.",
    "Aplomb: Self-confidence or assurance.",
    "Arbitrary: Based on random choice or personal whim.",
    "Arcane: Understood by few; mysterious or secret.",
    "Aspire: Direct one's hopes or ambitions toward achieving something.",
    "Assiduous: Showing great care and perseverance.",
    "Atrophy: Gradual decline in effectiveness due to underuse.",
    "Auspicious: Conducive to success; favorable.",
    "Austere: Severe or strict in manner or appearance.",
    "Avarice: Extreme greed for wealth or material gain.",
    "Benevolent: Well-meaning and kindly.",
    "Blatant: Done openly and unashamedly.",
    "Blithe: Showing a casual and cheerful indifference.",
    "Bolster: To support or strengthen.",
    "Boorish: Rough and bad-mannered.",
    "Brevity: Concise and exact use of words.",
    "Cacophony: A harsh, discordant mixture of sounds.",
    "Cajole: Persuade someone to do something by sustained coaxing.",
    "Callous: Showing or having an insensitive and cruel disregard for others.",
    "Candor: The quality of being open and honest.",
    "Capitulate: Cease to resist an opponent; surrender.",
    "Cathartic: Providing psychological relief through the open expression of strong emotions.",
    "Censure: Express severe disapproval of.",
    "Chagrin: Distress or embarrassment at having failed.",
    "Chicanery: Use of trickery to achieve a political, financial, or legal purpose.",
    "Circumspect: Wary and unwilling to take risks.",
    "Clemency: Mercy; lenience.",
    "Coalesce: Come together to form one mass or whole.",
    "Cognizant: Having knowledge or being aware of.",
    "Commensurate: Corresponding in size or degree.",
    "Compendium: A collection of concise but detailed information.",
    "Complacent: Showing smug satisfaction with oneself.",
    "Concur: Be of the same opinion; agree.",
    "Confluence: The junction of two rivers.",
    "Congenial: Pleasant because of a personality, qualities, or interests similar to one's own.",
    "Conspicuous: Standing out so as to be clearly visible.",
    "Contingent: Subject to chance.",
    "Contrite: Feeling or expressing remorse.",
    "Conundrum: A confusing and difficult problem.",
    "Copious: Abundant in supply or quantity.",
    "Corroborate: Confirm or give support to.",
    "Cursory: Hasty and therefore not thorough.",
    "Debilitate: Make someone weak and infirm.",
    "Decorum: Behavior in keeping with good taste.",
    "Deference: Humble submission and respect.",
    "Deleterious: Causing harm or damage.",
    "Demure: Reserved, modest, and shy.",
    "Deride: Express contempt for.",
    "Despot: A ruler who holds absolute power.",
    "Diaphanous: Light, delicate, and translucent.",
    "Didactic: Intended to teach, particularly having moral instruction.",
    "Diffident: Modest or shy due to lack of self-confidence.",
    "Dilatory: Slow to act.",
    "Disparate: Essentially different in kind.",
    "Dogmatic: Inclined to lay down principles as incontrovertibly true.",
    "Dubious: Hesitating or doubting.",
    "Eclectic: Deriving ideas from a broad and diverse range of sources.",
    "Efficacy: The ability to produce a desired result.",
    "Egregious: Outstandingly bad.",
    "Elucidate: Make something clear.",
    "Emulate: Match or surpass.",
    "Enervate: Cause someone to feel drained of energy.",
    "Engender: Cause or give rise to.",
    "Ephemeral: Lasting for a very short time.",
    "Equanimity: Mental calmness and composure.",
    "Equivocate: Use ambiguous language to conceal the truth.",
    "Erudite: Having or showing great knowledge.",
    "Eschew: Deliberately avoid using.",
    "Evanescent: Quickly fading or disappearing.",
    "Exacerbate: Make a problem worse.",
    "Exculpate: Show or declare that someone is not guilty.",
    "Exigent: Pressing; demanding.",
    "Exonerate: Absolve someone from blame.",
    "Expedient: Convenient and practical.",
    "Extol: Praise enthusiastically.",
    "Facetious: Treating serious issues with deliberately inappropriate humor.",
    "Fallacious: Based on a mistaken belief.",
    "Fastidious: Very attentive to accuracy and detail.",
    "Fatuous: Silly and pointless.",
    "Fecund: Producing an abundance of offspring or new growth.",
    "Fervent: Having or displaying passionate intensity.",
    "Flabbergasted: Extremely surprised or shocked.",
    "Flippant: Not showing a serious or respectful attitude.",
    "Fortuitous: Happening by a lucky chance.",
    "Fractious: Irritable and quarrelsome."
];

const generate=(()=>{
    let n = words.length;
let n1=Math.floor(Math.random()*n);
let n2=Math.floor(Math.random()*(n-2))+2;

let target = document.querySelector("#main").firstElementChild;
target.innerHTML=(`${words[n1]}<br><br>${words[n2]}`);
})

let btn=document.querySelector("#btn");
btn.addEventListener("click",generate);